import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.tuxdave.JChess.UI.GraphicalBoard;
import com.tuxdave.JChess.core.GameBoard;
import com.tuxdave.JChess.extras.Vector2;

import javax.swing.*;
import java.awt.*;

public class Test0 extends JFrame {
    private JPanel panel1;
    private GraphicalBoardTest gboard;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(gboard, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    {
        add(panel1);
        //create a custom board to make a test
        GameBoard board = new GameBoard();
        board.getPieceByPosition(new Vector2(4, 2)).move(new Vector2(4, 4));
        board.getPieceByPosition(new Vector2(4, 1)).move(new Vector2(4, 3));
        board.getPieceByPosition(new Vector2(7, 7)).move(new Vector2(7, 6));
        gboard.setBoard(board);
    }

    public static void main(String[] args) {
        Test0 t = new Test0();
        t.setResizable(false);
        t.setBounds(20, 20, 600, 600);
        t.setVisible(true);
        t.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public void createUIComponents() {
        gboard = new GraphicalBoardTest();
    }
}
